name: main_project
description: "A new Flutter project."
publish_to: 'none' # Specifies that this package is not intended for publishing to pub.dev
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  supabase_flutter: ^2.0.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
